// <auto-generated />
namespace EventReservation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class locals_images : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(locals_images));
        
        string IMigrationMetadata.Id
        {
            get { return "202001251915247_locals_images"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
